spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:  
      hibernate:  
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
  thymeleaf:
#    prefix: classpath:/templates/
    cache: false  
    encoding: UTF-8
    mode: HTML5

security:
  basic:
    enabled: false
