spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:  
      hibernate:  
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        
security:
  basic:
    enabled: false
