properties:
  project: oauth-jdbc-client
  env: production
  log-level: INFO
    
spring:
  datasource:
    url: jdbc:mysql://192.168.1.154:3306/dev_oauth_pro?characterEncoding=UTF-8
    username: dev
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver

