properties:
  project: oauth-sso-client
  env: dev
  log-level: DEBUG
  server:
    oauth: 127.0.0.1:8081
    api: 127.0.0.1:8082

server:
    session:
      cookie:
        name: UISESSION

spring:
  datasource:
    url: jdbc:mysql://192.168.1.151:3306/dev_oauth?characterEncoding=UTF-8
    username: dev
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver

security:
  oauth2:
    client:
      clientId: sso_service
      clientSecret: secret
      accessTokenUri: http://127.0.0.1:8081/oauth/token
      userAuthorizationUri: http://127.0.0.1:8081/oauth/authorize
    resource:
#      userInfoUri: http://127.0.0.1:8081/user/me
      filter-order: 3
      token-info-uri: http://127.0.0.1:8081/oauth/check_token
