properties:
  project: oauth-web-client
  env: production
  log-level: INFO

server:
    session:
      cookie:
        name: UISESSION

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dev_oauth?characterEncoding=UTF-8
    username: dev
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver

security:
  oauth2:
    client:
      clientId: sso_service
      clientSecret: secret
      accessTokenUri: http://${properties.server.oauth}/oauth/token
      userAuthorizationUri: http://${properties.server.oauth}/oauth/authorize
    resource:
#      userInfoUri: http://127.0.0.1:8081/user/me
      filter-order: 3
      token-info-uri: http://${properties.server.oauth}/oauth/check_token
