logging:
  level:
    org.springframework.security: DEBUG
    
spring:
  datasource:
    url: jdbc:mysql://192.168.1.151:3306/dev_oauth?characterEncoding=UTF-8
    username: dev
    password: 1qaz@WSX
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:  
      hibernate:  
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
  thymeleaf:
#    prefix: classpath:/templates/
    cache: false  
    encoding: UTF-8
    mode: HTML5
    
server:
  port: 8081
#  context-path: /auth
#  session:
#      cookie:
#        name: UISESSION
        
security:
  basic:
    enabled: false