server:
  port: 8084
  session:
    cookie:
      name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: sso_service
      clientSecret: secret
      accessTokenUri: http://127.0.0.1:8081/oauth/token
      userAuthorizationUri: http://127.0.0.1:8081/oauth/authorize
    resource:
      filter-order: 3
      token-info-uri: http://127.0.0.1:8081/oauth/check_token
spring:
  thymeleaf:
    cache: false  
    encoding: UTF-8
    mode: HTML5