properties:
  project: feign-test
  env: dev
  log-level: INFO
  server:
    oauth: 192.168.1.151:8081

ribbon:
  ReadTimeout:  30000
  ConnectTimeout:  15000
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

feign:
  hystrix:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000

security:
  oauth2:
    client:
      accessTokenUri: http://${properties.server.oauth}/oauth/token
      userAuthorizationUri: http://${properties.server.oauth}/oauth/authorize
      client-id: feign_service
      client-secret: secret
      grant-type: client_credentials
      #scope: read, write
    resource:
      token-info-uri: http://${properties.server.oauth}/oauth/check_token
      user-info-uri: http://${properties.server.oauth}/user
